#!/bin/bash

# Written by Nicolai Brand (lytix.dev) 05.01.2022

mem=$(free -h | awk '/^Mem:/ {print $3 "/" $2}')

case $BLOCK_BUTTON in
    1)
        notify-send "Memory" "$mem"
	;;
esac

# convert from Mi to Gb
if echo $mem | grep -q "Mi"; then
    simplified=$(echo $mem | sed 's/\//\/(/; s/Gi/\*10)/g; s/Mi//g; s/\.//g')
else
    simplified="$(echo $mem | sed 's/Gi//g; s/Mi//g')*100"
fi
echo "$simplified" | bc -l | cut -b 1-3 | sed 's/\..*//; s/$/%/'
