#!/bin/sh
# Written by Nicolai Brand (lytix.dev) 05.01.2022, 02.09.2022

main="/dev/nvme0n1p3"
data=$(df -h | grep $main)

case $BLOCK_BUTTON in
    1)
        info="mount\t\ttotal\tused\tfree"
        notify-send "Storage" "$info\n$data"
        ;;
esac

