#!/bin/sh
# Written by Nicolai H. Brand 2021 - 2024

case $BLOCK_BUTTON in
    1)
            notify-send "Weather" "$(curl -Ss 'https://wttr.in?0&T&Q' | tee "$CACHE_LOC")"
        ;;
esac

#curl -Ss 'https://wttr.in?0&T&Q' | cut -c 16- | head -2 | awk "/.*[0-9]/" | sed "s/\s//g; s/(.*)//"
slash "$HOME"/Scripts/eilor.slash
