#!/bin/sh
vol=$(amixer sget Master | awk '/^..Mono/ {print $4}' | sed 's/\[//; s/\]//; s/\%//')
new_vol=$(($vol + $1))

[ $new_vol -le 0 ] && new_vol=0

amixer set Master $new_vol%
pkill -SIGRTMIN+10 i3blocks
