#!/bin/env bash

current_song=$(cmus-remote -Q | awk 'NR==2')
difference=$(echo "$current_song" | diff  /tmp/current_song -)
echo "$current_song" > /tmp/current_song

while true
do
    sleep 1
    current_song=$(cmus-remote -Q | awk 'NR==2')
    difference=$(echo "$current_song" | diff  /tmp/current_song - 2>/dev/null)
    if [ "$difference" != "" ]
    then
        echo "$current_song" > /tmp/current_song
        pkill -SIGRTMIN+20 i3blocks
    fi
done
