#!/bin/sh

intern="eDP1"
extern="HDMI1"
highres="3840x2160"
p1080="1920x1080"

xrandr --output "$extern" --dpi 150 --set audio force-dvi --mode "$highres"
#xrandr --output "$intern" --auto --output "$extern" --left-of "$intern"
xrandr --output "$intern" --off   
