#!/bin/python3.9

from datetime import date


def main():
    cur_date = date.today()
    rating = int(input("rating (1-5)\n> "))
    comment = input("comment (type 0 if no comment)\n> ")

    with open("/home/nic/Documents/python-projects/happiness-tracker/data.csv", "r") as f:
        lines = f.readlines()
        last_line = lines[-1]
        last_date = last_line[0:last_line.find(",")]

        if last_date == str(date.today()):
            lines = lines[:-1]

        lines.append(f"{cur_date},{rating},{comment}\n")

    with open("/home/nic/Documents/python-projects/happiness-tracker/data.csv", "w") as f:
        for line in lines:
            f.write(line)


if __name__ == "__main__":
    main()
