#!/bin/sh
#free -h | awk '/^Mem:/ {print $3 "/" $2}' | sed 's/Gi/GB/g; s/Mi/MB/g'

mem=$(free -h | awk '/^Mem:/ {print $3 "/" $2}')

case $BLOCK_BUTTON in
    1)
        notify-send "Memory" "$mem"
	;;
esac

if echo $mem | grep -q "Mi"; then
    simplified=$(echo $mem | sed 's/\//\/(/; s/Gi/\*10)/g; s/Mi//g; s/\.//g')
else
    simplified="$(echo $mem | sed 's/Gi//g; s/Mi//g')"
    simplified="$simplified*100"
fi
echo "$(echo $simplified | bc -l | cut -b 1-3 | sed 's/\..*//')%"
