#!/bin/sh
#free -h | awk '/^Mem:/ {print $3 "/" $2}' | sed 's/Gi/GB/g; s/Mi/MB/g'

mem=$(free -h | awk '/^Mem:/ {print $3 "/" $2}')

case $BLOCK_BUTTON in
    1)
        notify-send "Memory" "$mem"
	;;
esac

simplified=$(echo $mem | sed 's/Gi//g; s/Mi//g; s/\.//g')
res=$(echo $simplified | bc -l | sed "s/\.//" | cut -b 1,2)

if echo $mem | grep -q "Mi" ; then
    res="$(echo $res | cut -b 1)%"
    echo $res
else
    echo $res%
fi
