#!/bin/sh
#free -h | awk '/^Mem:/ {print $3 "/" $2}' | sed 's/Gi/GB/g; s/Mi/MB/g'

mem=$(free -h | awk '/^Mem:/ {print $3 "/" $2}')

case $BLOCK_BUTTON in
		1)
			notify-send "Memory" "$mem"
			;;
esac

mem2=$(free -m | awk '/^Mem:/ {print $3 "/" $2}')
final=$(echo $mem2 | bc -l | cut -b 2-3 | sed 's/^0//')
echo "$final%"
