#!/bin/sh

main="/dev/sda2"

data=$(df -h | grep $main)

case $BLOCK_BUTTON in
		1)
			info="mount,            total, used, free, %"
			notify-send "Storage" "$info\n$data"
			;;
esac

echo $data | cut -d " " -f 5

