#!/bin/sh
# Nicolai Brand (lytixdev) 2021-2022

IMAGE=/tmp/i3lock.png
LOCK=~/Pictures/lock.png
BLURTYPE="2x8"

scrot $IMAGE
convert $IMAGE -blur $BLURTYPE $IMAGE
convert $IMAGE $LOCK -gravity center -composite $IMAGE
i3lock -i $IMAGE
rm $IMAGE

#while pgrep i3lock &>/dev/null 
#do
#	sleep 1
#done
#notify-send "Welcome back, Nicolai"
