#!/bin/sh
# Nicolai Brand (lytixdev) 2021-2022

DIR="$HOME/Pictures/screenshots"
NAME="$DIR/$(date +"%Y-%m-%d-%H%M%S").png"
PID="nic_screenshot"

mkdir -p "$DIR"

if [ "$1" = "-a" ]
then
    # snipping tool-esque
    bash -c "exec -a $PID gnome-screenshot -a -f $NAME"
    # stupid wait for screenshot to be taken
    while test -d /proc/$PID; do
         sleep 0.2
    done
else
    scrot -F "$NAME"
fi

notify-send -t 3000 "Took screenshot [$NAME] succesfully"
echo "$NAME" | xclip -selection "clipboard"
