#!/bin/sh
# Nicolai Brand (lytixdev) 2021-2022

DIR="$HOME/Pictures/screenshots"
NAME="$DIR/$(date +"%Y-%m-%d-%H%M%S").png"

mkdir -p "$DIR"

if [ "$1" = "-a" ]
then
    # snipping tool-esque
    gnome-screenshot -a -f "$NAME"
    # stupid wait for screenshot to be taken
    #while test -d /proc/"$(pidof gnome-screenshot)"
    #do
    #     sleep 0.2
    #done
else
    scrot -F "$NAME"
fi

notify-send -t 3000 "Took screenshot [$NAME] succesfully"
echo "$NAME" | xclip -selection "clipboard"
