#!/bin/sh
# Script that lets me choice what monitor configuration I want to use
# Starts on x login

intern="eDP1"
extern="HDMI1"
term_conf="/home/nic/.config/kitty"

choice=$(printf "intern\nextern1080p+intern\nextern1440p+intern\nextern4k+intern\nmirror1080p\nextern1080p\nextern1440p\nsmart\n" | dmenu)

case $choice in
    "intern")
        xrandr | grep -q "$extern connected" && 
        xrandr --output $extern --off &&
        xrandr --output $intern --auto --primary &&
        cp $term_conf/kitty_std.conf $term_conf/kitty.conf
        ;;
        
    "extern1080p+intern")
        xrandr | grep -q "$extern connected" &&
        xrandr --output $extern --set audio force-dvi --mode "1920x1080" --primary &&
        xrandr --output $intern --auto --output $extern --left-of $intern &&
        cp $term_conf/kitty_std.conf $term_conf/kitty.conf ||
        notify-send "Monitor $extern not connected"
        ;;

    "extern1440p+intern")
        xrandr | grep -q "$extern connected" &&
        xrandr --output $intern --auto --output $extern --left-of $intern &&
        cp $term_conf/kitty_hdpi.conf $term_conf/kitty.conf ||
        notify-send "Monitor $extern not connected" 
        ;;

    "extern4k+intern")
        xrandr | grep -q "$extern connected" &&
        xrandr --output $extern --set audio force-dvi --mode "3840x2160" --primary &&
        xrandr --output $intern --auto --output $extern --left-of $intern &&
        cp $term_conf/kitty_hdpi.conf $term_conf/kitty.conf ||
        notify-send "Monitor $extern not connected"
        ;;

    "mirror1080p")
        xrandr | grep -q "$extern connected" &&
        xrandr --output $extern --set audio force-dvi --mode "1920x1080" &&
        cp $term_conf/kitty_std.conf $term_conf/kitty.conf ||
        notify-send "Monitor $extern not connected"
        ;;

    "extern1080p")
        xrandr | grep -q "$extern connected" && 
        xrandr --output $extern --set audio force-dvi --mode "1920x1080" --primary &&
        xrandr --output $intern --off &&
        cp $term_conf/kitty_std.conf $term_conf/kitty.conf
        ;;

    "extern1440p")
        xrandr | grep -q "$extern connected" && 
        xrandr --output $extern --set audio force-dvi --mode "2560x1440" --primary &&
        xrandr --output $intern --off &&
        cp $term_conf/kitty_hdpi.conf $term_conf/kitty.conf
        ;;
    "smart")
        xrandr --auto
        cp $term_conf/kitty_std.conf $term_conf/kitty.conf
        ;;
esac

# changes to display settings usually causes i3 to get confused
sleep 1.5
i3-msg reload > /dev/null
