#!/bin/sh

# static part of the url
a="https://tp.uio.no/ntnu/timeplan/?id=22422&type=student&week="
b="&weekTo=52&ar="

# gets current week and year
week=$(date +"%V")
year=$(date +"%Y")

link="$a$week$b$year"

echo "$link" && firefox "$link"
